name: docker image testing

on:
  push:
    branches:
      - master
      - mseed
  pull_request:
    branches:
      - master
      - mseed

jobs:
  Docker-tests:
    runs-on: ubuntu-20.04
      
    steps:  

        # aws-region: us-east-2
      - uses: actions/checkout@v3
      - name: start containers
        env: 
          AWSACCESSKEYID: ${{ secrets.AWSACCESSKEYID }}
          AWSSECRETACCESSKEY: ${{ secrets.AWSSECRETACCESSKEY }}
        run: docker-compose --version && cd mseed/ && docker-compose up --build

       
      - name: clean up containers
        run: docker-compose down
        
