version: "3"
services:
  fetch:
    image: orcastream/orcamseed
    build: ./
    command: tail -F README.md
    restart: always
#    env_file: .env
    volumes:
      - data:/tmp
    depends_on:
      - upload

  upload:
    image: orcastream/orcamseed
    build: ./
    command: ./streamfiles.sh
    restart: always

    environment:
      - AWSACCESSKEYID=${AWSACCESSKEYID}
      - AWSSECRETACCESSKEY=${AWSSECRETACCESSKEY}  
      - NODE_NAME=${NODE_NAME} 
#    env_file: .env
    volumes:
      - data:/tmp
    privileged: true
  

volumes:
  data:
